version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: install watchman
          command: |
            echo "deb http://http.us.debian.org/debian testing main non-free contrib" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install watchman
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: npm run build && npm test
workflows:
  version: 2
  test:
    jobs:
      - test
